server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cloudstudy
    username: root
    password: password
  application:
    name: book-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848