server:
  port: 8301
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cloudstudy
    username: root
    password: password
security:
  oauth2:
    client:
      client-id: web
      client-secret: 654321
      # token获取地址
      access-token-uri: http://localhost:8500/sso/oauth/token
      # 验证页面地址
      user-authorization-uri: http://localhost:8500/sso/oauth/authorize
    resource:
      # token信息获取和校验地址
      token-info-uri: http://localhost:8500/sso/oauth/check_token