server:
  port: 8101
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cloudstudy
    username: root
    password: password
  application:
    name: userService
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka