server:
  port: 8201
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/cloudstudy
    username: root
    password: password
  application:
    name: borrow-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: false
        cluster-name: Chengdu
    loadbalancer:
      nacos:
        enabled: true